

FROM ubuntu:latest

RUN apt update && apt install -y \
    python3 python3-pip imagemagick \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ../Q2/plant2.py /app/plant2.py
COPY ../Q2/requirements.txt /app/requirements.txt

RUN pip install --break-system-packages -r /app/requirements.txt

ENTRYPOINT ["python3", "/app/plant2.py"]
